import Providers from "@/contexts/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Desafio - Fullstack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
